---
podman_volumes_traefik:
  traefik:
    - 'traefik_config'

podman_networks_traefik:
  traefik:
    - 'traefik-backend'

podman_service_containers_traefik:
  traefik:
    traefik:
      image: 'docker.io/library/traefik:latest'
      ports:
        - '7000:8080'
        - '7443:443'
      command:
        - 'traefik'
        - '--api.insecure=true'
        - '--entrypoints.websecure.address=:443'
        - '--providers.docker'
        - '--providers.docker.watch'
        - '--providers.docker.network=traefik-backend'
        - '--providers.docker.exposedByDefault=false'
      network:
        - 'traefik-backend.network'
      volume:
        - "/run/user/{{ podman_user_uid }}/podman/podman.sock:/var/run/docker.sock:Z"
        - 'traefik_config:/etc/traefik:Z'
      cap_add:
        - 'NET_ADMIN'
      security_opt:
        - 'label=disable'
