---
- name: 'Add service to changelist'  # noqa no-handler
  ansible.builtin.set_fact:
    podman_services_changed: "{{ podman_services_changed + [service['name']] }}"
  when:
    - service_config['changed']
    - service['state'] | default('present') == 'present'
