---
- name: 'Deploy services'
  ansible.builtin.include_tasks: "services/{{ service['name'] }}.yml"
  loop: "{{ podman_services }}"
  loop_control:
    loop_var: 'service'

- name: 'Workaround - remove services'
  ansible.builtin.include_tasks: 'workaround_remove.yml'
  when: service['state'] | default('present') == 'absent'
  loop: "{{ podman_services }}"
  loop_control:
    loop_var: 'service'
