---
- name: 'Restart changed containers'
  ansible.builtin.systemd:
    name: "{{ container }}"
    state: 'restarted'
    daemon_reload: true
    scope: "{{ (podman_user_account != 'root') | ternary('user', 'system') }}"
  become: "{{ (podman_user_account != 'root') | ternary(true, omit) }}"
  become_user: "{{ podman_user_account }}"
  loop: "{{ podman_containers[service] }}"
  loop_control:
    loop_var: 'container'
