---
- name: 'Workaround - Remove quadlets for removed containers'
  ansible.builtin.file:
    path: "{{ (ansible_facts['effective_user_id'] > 0) | ternary('~/.config', '/etc') }}/containers/systemd/{{ container }}.container"
    state: 'absent'
  loop: "{{ podman_containers[service['name']] }}"
  loop_control:
    loop_var: 'container'

- name: 'Workaround - Remove quadlets for removed volumes'
  ansible.builtin.file:
    path: "{{ (ansible_facts['effective_user_id'] > 0) | ternary('~/.config', '/etc') }}/containers/systemd/{{ volume }}.volume"
    state: 'absent'
  loop: "{{ podman_volumes[service['name']] }}"
  loop_control:
    loop_var: 'volume'

- name: 'Workaround - Remove quadlets for removed networks'
  ansible.builtin.file:
    path: "{{ (ansible_facts['effective_user_id'] > 0) | ternary('~/.config', '/etc') }}/containers/systemd/{{ network }}.network"
    state: 'absent'
  loop: "{{ podman_networks[service['name']] }}"
  loop_control:
    loop_var: 'network'

- name: 'Reload systemd config'
  ansible.builtin.systemd:
    daemon_reload: true
    daemon_reexec: true
    scope: "{{ (ansible_facts['effective_user_id'] > 0) | ternary('user', 'system', 'system') }}"
