---
- name: Ensure container - {{ service['name'] }}-geth
  containers.podman.podman_container:
    name: "{{ service['name'] }}-geth"
    image: docker.io/ethereum/client-go:stable
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    command:
      - --state.scheme=path
      - --cache=4096
      - --datadir=/ethereum/execution/data
      - --ws
      - --ws.origins=*
      - --ws.api=eth,net,web3,debug
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=eth,net,engine,admin,web3
      - --syncmode=snap
      - --gcmode=full
      - --authrpc.vhosts=*
      - --mainnet
    auto_remove: true
    timezone: Europe/Amsterdam
    user: 1001:1002
    network:
      - "{{ service['name'] }}-backend.network"
    ports:
      - 30303:30303/tcp
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 8547:8547/tcp
    pull: newer
    quadlet_options: "{{ podman_quadlet_options }}"
    volume:
      - "{{ service['name'] }}:/ethereum"
    healthcheck: wget --no-verbose --tries=1 --spider http://localhost:8545 || exit 1
    healthcheck_interval: 60s
    healthcheck_start_period: 5m
  register: service_config
  notify: Restart changed services

- name: Ensure container - {{ service['name'] }}-beacon
  containers.podman.podman_container:
    name: "{{ service['name'] }}-beacon"
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    command:
      - --datadir=/ethereum/execution/data
      - --execution-endpoint=/ethereum/execution/data/geth.ipc
      - --grpc-gateway-host=0.0.0.0
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --accept-terms-of-use
      - --suggested-fee-recipient=0x4D5F4A853000B9e7Be86aDf115576713d654F8C6
      - --checkpoint-sync-url=https://beaconstate-mainnet.chainsafe.io
      - --genesis-beacon-api-url=https://beaconstate-mainnet.chainsafe.io
    auto_remove: true
    timezone: Europe/Amsterdam
    user: 1001:1002
    network:
      - "{{ service['name'] }}-backend.network"
    ports:
      - 3500:3500/tcp
      - 4000:4000/tcp
      - 8080:8080/tcp
      - 13000:13000/tcp
      - 12000:12000/udp
    pull: newer
    quadlet_options: "{{ podman_quadlet_options }}"
    cap_add:  # Voeg deze sectie toe om capabilities toe te voegen
      - NET_ADMIN  # Voeg hier de gewenste capabilities toe
    volume:
      - "{{ service['name'] }}:/ethereum"
  register: service_config
  notify: Restart changed services

- name: Ensure container - {{ service['name'] }}-validator
  containers.podman.podman_container:
    name: "{{ service['name'] }}-validator"
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    command:
      - --wallet-dir=/ethereum/consensus/validator_keys
      - --wallet-password-file=/ethereum/consensus/validator_keys/wallet.txt
      - --web
      - --grpc-gateway-host=0.0.0.0
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - "--beacon-rpc-provider={{ service['name'] }}-beacon:4000"
      - --accept-terms-of-use
      - --suggested-fee-recipient=0x4D5F4A853000B9e7Be86aDf115576713d654F8C6
    auto_remove: true
    timezone: Europe/Amsterdam
    network:
      - "{{ service['name'] }}-backend.network"
    ports:
      - 7500:7500/tcp
      - 8081:8081/tcp
    pull: newer
    quadlet_options: "{{ podman_quadlet_options }}"
    volume:
      - "{{ service['name'] }}:/ethereum"
  register: service_config
  notify: Restart changed services

- name: Set up network
  ansible.builtin.import_tasks: ../network.yml

- name: Add to changed service list
  ansible.builtin.import_tasks: ../changed_service.yml
