---
- name: "Ensure container - {{ service['name'] }}"
  containers.podman.podman_container:
    name: "{{ service['name'] }}"
    image: 'docker.io/grafana/grafana:latest'
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    auto_remove: true
    ports:
      - "{{ grafana_listen_uri }}:3000"
    pull: 'newer'
    volume:
      - "{{ service['name'] }}:/var/lib/grafana:Z"
    network:
      - 'grafana-backend.network'
    quadlet_options: "{{ podman_quadlet_options }}"
  register: service_config
  notify: 'Restart changed services'

- name: 'Set up volume'
  ansible.builtin.import_tasks: '../volume.yml'

- name: 'Set up network'
  ansible.builtin.import_tasks: '../network.yml'

- name: 'Add to changed service list'
  ansible.builtin.import_tasks: '../changed_service.yml'
