---
- name: 'Ensure container'
  containers.podman.podman_container:
    name: 'hello_world'
    image: 'thomaspoignant/hello-world-rest-json'
    state: 'started'
    auto_remove: true
    ports:
      - '8080:8080'
