---
- name: "Ensure container - {{ service['name'] }}"
  containers.podman.podman_container:
    name: "{{ service['name'] }}"
    image: "{{ kanboard_image_uri }}:{{ kanboard_version }}"
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    auto_remove: true
    #env:
    ports:
      - "{{ kanboard_listen_uri }}:3000"
    pull: 'newer'
    quadlet_options: "{{ podman_quadlet_options }}"
    volume:
      - "{{ service['name'] }}:/data:Z"
  register: 'service_config'

- name: 'Set up volume'
  ansible.builtin.import_tasks: '../volume.yml'

- name: 'Add to changed service list'
  ansible.builtin.import_tasks: '../changed_service.yml'
