---
- name: "Ensure container - {{ service['name'] }}"
  containers.podman.podman_container:
    name: "{{ service['name'] }}"
    image: 'quay.io/openbao/openbao'
    state: "{{ (service['state'] | default('present') == 'present') | ternary('quadlet', 'absent') }}"
    auto_remove: true
    command:
      - 'server'
      - '-config=/openbao/config/config.hcl'
    cap_add:
      - 'IPC_LOCK'
    ports:
      - '8200:8200'
    pull: 'newer'
    quadlet_options: "{{ podman_quadlet_options }}"
    volume:
      - "{{ service['name'] }}_config:/openbao/config:Z"
      - "{{ service['name'] }}_data:/openbao/file:Z"
  register: service_config
  notify: 'Restart changed services'

- name: 'Set up volume'
  ansible.builtin.import_tasks: '../volume.yml'

- name: 'Set up config file'
  when: service['state'] == 'present'
  block:
    - name: 'Get volume information'
      containers.podman.podman_volume_info:
        name: "{{ service['name'] }}_config"
      register: 'volume_info'

    - name: 'Ensure config file'
      ansible.builtin.command:
        cmd: >-
          podman unshare cp "{{ role_path }}/files/openbao/config.hcl"
          {{ volume_info['volumes'][0]['Mountpoint'] }}/config.hcl
      args:
        creates: "{{ volume_info['volumes'][0]['Mountpoint'] }}/config.hcl"

- name: 'Add to changed service list'
  ansible.builtin.import_tasks: '../changed_service.yml'
